package it.polimi.ingsw.network.clientMessage;

public enum PlayerActionEnum {
    GETGAMES,
    CREATEGAME,
    JOINGAME,
    CHOOSEPLAYERCOLOR,
    PLACECARD,
    DRAWCARDFROMFIELD,
    DRAWCARDFROMRESOURCEDECK,
    DRAWCARDFROMGOLDDECK,
    SWITCHCARDSIDE,
    SETPLAYEROBJECTIVE
}
