package it.polimi.ingsw.tui.commandLine;

public enum ClientStatusEnum {
    //MAIN_MENU, JOIN_GAME, CREATE_GAME, DELETE_GAME, GET_GAMES,
    MAIN_MENU, GET_GAMES, INIT_PLACE_STARTER_CARD, INIT_CHOOSE_PLAYER_COLOR, INIT_CHOOSE_OBJECTIVE_CARD, PLACE_CARD, DRAW_CARD, GAME_OVER;
}
