name: Java CI with Maven and Release

on:
  push:
    branches: [ pier_build-action ]
permissions:
  contents: write
jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          maven-version: '3.9.6'
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml -D javafx.platform=mac
      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/jars/CodexNaturalis-client-jar-with-dependencies.jar
            ./target/jars/CodexNaturalis-server-jar-with-dependencies.jar
            ./target/CodexNaturalis-win-client.zip
            ./target/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}