name: Java CI with Maven and Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  mac-build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          maven-version: '3.9.6'
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml -D javafx.platform=mac
      - name: Rename DMG file
        run: mv ./target/*.dmg ./target/CodexNaturalis-mac-x86-${{ github.ref_name }}.dmg
      - name: Rename client JAR file
        run: mv ./target/jars/CodexNaturalis-client-jar-with-dependencies.jar ./target/jars/CodexNaturalis-client-mac-${{ github.ref_name }}.jar
      - name: Rename server JAR file
        run: mv ./target/jars/CodexNaturalis-server-jar-with-dependencies.jar ./target/jars/CodexNaturalis-server-${{ github.ref_name }}.jar
      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/jars/CodexNaturalis-client-mac-${{ github.ref_name }}.jar
            ./target/jars/CodexNaturalis-server-${{ github.ref_name }}.jar
            ./target/CodexNaturalis-mac-x86-${{ github.ref_name }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  win-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          maven-version: '3.9.6'
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml -D javafx.platform=win
      - name: Rename client JAR file
        run: mv ./target/jars/CodexNaturalis-client-jar-with-dependencies.jar ./target/jars/CodexNaturalis-client-win-${{ github.ref_name }}.jar
      - name: Rename ZIP file
        run: mv ./target/CodexNaturalis-win-client.zip ./target/CodexNaturalis-win-client-${{ github.ref_name }}.zip
      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/jars/CodexNaturalis-client-win-${{ github.ref_name }}.jar
            ./target/CodexNaturalis-win-client-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          maven-version: '3.9.6'
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Create Javadoc ZIP file
        run: zip -r ./target/CodexNaturalis-javadoc-${{ github.ref_name }}.zip ./target/site/apidocs/
      - name: Upload Javadoc to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/CodexNaturalis-javadoc-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}