name: Deploy on release

on:
  push:
    branches:
      - pier_docker-build

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Copy files to server
        run: |
          scp docker-compose.yml ${{secrets.DEPLOY_USERNAME}}@${{vars.DEPLOY_IP}}:/codexNaturalis/docker-compose.yml
          scp deploy.sh ${{secrets.DEPLOY_USERNAME}}@${{vars.DEPLOY_IP}}:/codexNaturalis/deploy.sh

      - name: Deploy to server
        run: |
          ssh ${{secrets.DEPLOY_USERNAME}}@${{vars.DEPLOY_IP}} 'chmod +x /codexNaturalis/deploy.sh && /codexNaturalis/deploy.sh ${{secrets.GHCR_USERNAME}} ${{secrets.GHCR_AUTH_TOKEN}}'